// CloudBoard.Vue/src/views/cloudboard/CloudboardEdit.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import Dialog from 'primevue/dialog';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Button from 'primevue/button';
import ProgressSpinner from 'primevue/progressspinner';
import { useToast } from 'primevue/usetoast';
import type { CloudBoard } from '@/models/cloudboard';
import * as cloudboardService from '@/services/cloudboardService';

const props = defineProps<{ cloudBoard: CloudBoard | null }>();
const emit = defineEmits<{ boardUpdated: [board: CloudBoard]; editCancelled: [] }>();
const visible = defineModel<boolean>('visible', { default: false });

const toast = useToast();

const editingBoard = ref<CloudBoard | null>(null);
const shareEmail = ref('');
const sharedUsers = ref<string[]>([]);
const isSaving = ref(false);

watch([visible, () => props.cloudBoard], ([isVisible, cloudBoard]) => {
  if (isVisible && cloudBoard) {
    editingBoard.value = { ...cloudBoard, description: cloudBoard.description || '' };
    void loadSharedUsers(cloudBoard.id);
  } else if (!isVisible) {
    resetForm();
  }
});

function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

async function saveEdit(): Promise<void> {
  if (!editingBoard.value || !editingBoard.value.name?.trim()) {
    toast.add({ severity: 'warn', summary: 'Validation Error', detail: 'Board name is required' });
    return;
  }

  isSaving.value = true;
  try {
    const updatedBoard = await cloudboardService.updateCloudBoard(editingBoard.value);
    await saveShareSettings(updatedBoard.id);

    toast.add({ severity: 'success', summary: 'Success', detail: 'Board updated successfully' });

    emit('boardUpdated', updatedBoard);
    closeDialog();
  } catch (error) {
    console.error('Error updating cloudboard', error);
    toast.add({ severity: 'error', summary: 'Error', detail: 'Failed to update board' });
  } finally {
    isSaving.value = false;
  }
}

function cancelEdit(): void {
  emit('editCancelled');
  closeDialog();
}

function closeDialog(): void {
  visible.value = false;
  resetForm();
}

function resetForm(): void {
  editingBoard.value = null;
  shareEmail.value = '';
  sharedUsers.value = [];
  isSaving.value = false;
}

function addShareUser(): void {
  if (shareEmail.value && isValidEmail(shareEmail.value)) {
    if (!sharedUsers.value.includes(shareEmail.value)) {
      sharedUsers.value.push(shareEmail.value);
      shareEmail.value = '';
    } else {
      toast.add({ severity: 'warn', summary: 'Warning', detail: 'User is already in the share list' });
    }
  }
}

function removeShareUser(email: string): void {
  sharedUsers.value = sharedUsers.value.filter((user) => user !== email);
}

async function loadSharedUsers(boardId: string): Promise<void> {
  sharedUsers.value = await cloudboardService.getSharedUsers(boardId);
}

async function saveShareSettings(boardId: string): Promise<void> {
  await cloudboardService.updateSharing(boardId, sharedUsers.value);
}
</script>

<template>
  <Dialog
    header="Edit CloudBoard"
    v-model:visible="visible"
    modal
    closable
    :draggable="false"
    :resizable="false"
    class="w-96"
  >
    <div v-if="editingBoard" class="flex flex-col gap-4">
      <div class="flex flex-col gap-2">
        <label for="boardName" class="font-semibold text-sm">Board Name</label>
        <input
          id="boardName"
          type="text"
          class="p-inputtext w-full"
          v-model="editingBoard.name"
          placeholder="Enter board name"
          :disabled="isSaving"
        />
      </div>

      <div class="flex flex-col gap-2">
        <label for="boardDescription" class="font-semibold text-sm">Description</label>
        <Textarea
          id="boardDescription"
          v-model="editingBoard.description"
          placeholder="Enter board description (optional)"
          rows="3"
          class="w-full"
          :disabled="isSaving"
        />
      </div>

      <div class="flex flex-col gap-2">
        <label class="font-semibold text-sm">Share with Users</label>
        <div class="flex gap-2">
          <InputText
            type="email"
            v-model="shareEmail"
            placeholder="Enter email address"
            class="flex-1"
            :disabled="isSaving"
          />
          <Button
            icon="pi pi-plus"
            @click="addShareUser"
            :disabled="!shareEmail || !isValidEmail(shareEmail) || isSaving"
            size="small"
          />
        </div>

        <div v-if="sharedUsers.length > 0" class="flex flex-col gap-1 mt-2">
          <span class="text-sm text-gray-600">Shared with:</span>
          <div v-for="user in sharedUsers" :key="user" class="flex items-center justify-between bg-gray-100 px-3 py-2 rounded">
            <span class="text-sm">{{ user }}</span>
            <i
              class="pi pi-times cursor-pointer text-red-600 hover:text-red-800"
              :class="{ 'pointer-events-none': isSaving, 'opacity-50': isSaving }"
              @click="removeShareUser(user)"
            ></i>
          </div>
        </div>
      </div>
    </div>
    <div v-else class="flex items-center justify-center p-4">
      <ProgressSpinner stroke-width="4" animation-duration="1s" />
    </div>

    <template #footer>
      <Button label="Cancel" icon="pi pi-times" @click="cancelEdit" severity="secondary" :disabled="isSaving" />
      <Button
        label="Save"
        icon="pi pi-check"
        @click="saveEdit"
        :loading="isSaving"
        :disabled="!editingBoard || !editingBoard.name?.trim()"
      />
    </template>
  </Dialog>
</template>

// CloudBoard.Angular/src/app/cloudboard/cloudboard-edit/cloudboard-edit.component.ts
import { Component, EventEmitter, Input, Output, inject } from '@angular/core';
import { DialogModule } from 'primeng/dialog';
import { InputTextModule } from 'primeng/inputtext';
import { TextareaModule } from 'primeng/textarea';
import { ButtonModule } from 'primeng/button';
import { ProgressSpinnerModule } from 'primeng/progressspinner';
import { FormsModule } from '@angular/forms';
import { CommonModule } from '@angular/common';
import { CloudBoard } from '../models/cloudboard';
import { CloudboardService } from '../services/cloudboard.service';
import { MessageService } from 'primeng/api';

@Component({
  selector: 'cloudboard-edit',
  standalone: true,
  imports: [
    ButtonModule,
    CommonModule,
    FormsModule,
    DialogModule,
    InputTextModule,
    TextareaModule,
    ProgressSpinnerModule
  ],
  templateUrl: './cloudboard-edit.component.html',
  styleUrl: './cloudboard-edit.component.css'
})
export class CloudboardEditComponent {
  @Input() visible: boolean = false;
  @Input() cloudBoard: CloudBoard | null = null;
  @Output() visibleChange = new EventEmitter<boolean>();
  @Output() boardUpdated = new EventEmitter<CloudBoard>();
  @Output() editCancelled = new EventEmitter<void>();

  private cloudboardService = inject(CloudboardService);
  private messageService = inject(MessageService);

  public editingBoard: CloudBoard | null = null;
  public shareEmail: string = '';
  public sharedUsers: string[] = [];
  public isSaving: boolean = false;

  ngOnChanges(): void {
    if (this.visible && this.cloudBoard) {
      // Create a deep copy for editing
      this.editingBoard = {
        ...this.cloudBoard,
        description: this.cloudBoard.description || ''
      };
      // Load shared users
      this.loadSharedUsers(this.cloudBoard.id!);
    } else if (!this.visible) {
      this.resetForm();
    }
  }

  saveEdit(): void {
    if (!this.editingBoard || !this.editingBoard.name?.trim()) {
      this.messageService.add({
        severity: 'warn',
        summary: 'Validation Error',
        detail: 'Board name is required'
      });
      return;
    }

    this.isSaving = true;

    this.cloudboardService.updateCloudBoard(this.editingBoard).subscribe({
      next: (updatedBoard) => {
        // Save sharing settings
        this.saveShareSettings(updatedBoard.id!);

        this.messageService.add({
          severity: 'success',
          summary: 'Success',
          detail: 'Board updated successfully'
        });

        this.boardUpdated.emit(updatedBoard);
        this.closeDialog();
      },
      error: (error) => {
        console.error('Error updating cloudboard', error);
        this.messageService.add({
          severity: 'error',
          summary: 'Error',
          detail: 'Failed to update board'
        });
      },
      complete: () => {
        this.isSaving = false;
      }
    });
  }

  cancelEdit(): void {
    this.editCancelled.emit();
    this.closeDialog();
  }

  private closeDialog(): void {
    this.visible = false;
    this.visibleChange.emit(false);
    this.resetForm();
  }

  private resetForm(): void {
    this.editingBoard = null;
    this.shareEmail = '';
    this.sharedUsers = [];
    this.isSaving = false;
  }

  addShareUser(): void {
    if (this.shareEmail && this.isValidEmail(this.shareEmail)) {
      if (!this.sharedUsers.includes(this.shareEmail)) {
        this.sharedUsers.push(this.shareEmail);
        this.shareEmail = '';
      } else {
        this.messageService.add({
          severity: 'warn',
          summary: 'Warning',
          detail: 'User is already in the share list'
        });
      }
    }
  }

  removeShareUser(email: string): void {
    this.sharedUsers = this.sharedUsers.filter(user => user !== email);
  }

  isValidEmail(email: string): boolean {
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    return emailRegex.test(email);
  }

  private loadSharedUsers(boardId: string): void {
    // TODO: Implement API call to load shared users
    this.sharedUsers = [];
    
    // Example API call:
    // this.cloudboardService.getSharedUsers(boardId).subscribe({
    //   next: (users) => this.sharedUsers = users,
    //   error: (error) => console.error('Error loading shared users', error)
    // });
  }

  private saveShareSettings(boardId: string): void {
    // TODO: Implement API call to save sharing settings
    
    // Example API call:
    // this.cloudboardService.updateSharing(boardId, this.sharedUsers).subscribe({
    //   next: () => console.log('Sharing settings saved'),
    //   error: (error) => console.error('Error saving sharing settings', error)
    // });
  }
}

<p-dialog 
    header="Edit CloudBoard" 
    [(visible)]="visible"
    (visibleChange)="visibleChange.emit($event)"
    [modal]="true" 
    [closable]="true"
    [draggable]="false"
    [resizable]="false"
    styleClass="w-96">

    @if (editingBoard) {
    <div class="flex flex-col gap-4">
        <!-- Board Name Section -->
        <div class="flex flex-col gap-2">
            <label for="boardName" class="font-semibold text-sm">Board Name</label>
            <input 
                id="boardName" 
                type="text" 
                pInputText 
                [(ngModel)]="editingBoard.name" 
                placeholder="Enter board name"
                class="w-full"
                [disabled]="isSaving" />
        </div>

        <!-- Board Description Section -->
        <div class="flex flex-col gap-2">
            <label for="boardDescription" class="font-semibold text-sm">Description</label>
            <textarea 
                id="boardDescription" 
                pTextarea 
                [(ngModel)]="editingBoard.description"
                placeholder="Enter board description (optional)" 
                rows="3"
                class="w-full"
                [disabled]="isSaving"></textarea>
        </div>

        <!-- Sharing Section -->
        <div class="flex flex-col gap-2">
            <label class="font-semibold text-sm">Share with Users</label>
            <div class="flex gap-2">
                <input 
                    type="email" 
                    pInputText 
                    [(ngModel)]="shareEmail" 
                    placeholder="Enter email address"
                    class="flex-1"
                    [disabled]="isSaving" />
                <p-button 
                    icon="pi pi-plus" 
                    (click)="addShareUser()"
                    [disabled]="!shareEmail || !isValidEmail(shareEmail) || isSaving" 
                    size="small">
                </p-button>
            </div>

            <!-- Shared Users List -->
            @if (sharedUsers.length > 0) {
            <div class="flex flex-col gap-1 mt-2">
                <span class="text-sm text-gray-600">Shared with:</span>
                @for (user of sharedUsers; track user) {
                <div class="flex items-center justify-between bg-gray-100 px-3 py-2 rounded">
                    <span class="text-sm">{{user}}</span>
                    <i class="pi pi-times cursor-pointer text-red-600 hover:text-red-800"
                       (click)="removeShareUser(user)"
                       [class.pointer-events-none]="isSaving"
                       [class.opacity-50]="isSaving"></i>
                </div>
                }
            </div>
            }
        </div>
    </div>
    } @else {
    <div class="flex items-center justify-center p-4">
        <p-progressSpinner strokeWidth="4" animationDuration="1s"></p-progressSpinner>
    </div>
    }

    <ng-template pTemplate="footer">
        <p-button 
            label="Cancel" 
            icon="pi pi-times" 
            (click)="cancelEdit()" 
            severity="secondary"
            [disabled]="isSaving">
        </p-button>
        <p-button 
            label="Save" 
            icon="pi pi-check" 
            (click)="saveEdit()" 
            [loading]="isSaving"
            [disabled]="!editingBoard || !editingBoard.name?.trim()">
        </p-button>
    </ng-template>
</p-dialog>
