// CloudBoard.Angular/src/app/cloudboard/nodes/simple-note/simple-note.component.ts
import { Component } from '@angular/core';
import { CardModule } from 'primeng/card';
import { FormsModule } from '@angular/forms';
import { FFlowModule } from '@foblex/flow';
import { TextareaModule } from 'primeng/textarea';

import { BaseNodeComponent } from '../base-node.component';
import { Node, NoteProperties } from '../../models/cloudboard';

@Component({
  selector: 'simple-note',
  standalone: true,
  imports: [
    FFlowModule, 
    CardModule,
    FormsModule,
    TextareaModule
  ],
  templateUrl: './simple-note.component.html',
  styleUrl: './simple-note.component.css'
})
export class SimpleNoteComponent extends BaseNodeComponent {
  // Get content with default value if not set
  get content(): string {
    return this.getProperty<string>('content', 'Empty note...');
  }
  
  // Set content property
  set content(value: string) {
    this.updateProperty('content', value);
  }
  
  // Get background color with default value if not set
  get backgroundColor(): string {
    return this.getProperty<string>('backgroundColor', 'rgb(255, 249, 212)');
  }
  
  // Set background color property
  set backgroundColor(value: string) {
    this.updateProperty('backgroundColor', value);
  }
  
  // Get text color with default value if not set
  get textColor(): string {
    return this.getProperty<string>('textColor', '#000000');
  }
  
  // Set text color property
  set textColor(value: string) {
    this.updateProperty('textColor', value);
  }
}

<div class="simple-note shadow-md" [style]="{'background-color': backgroundColor, 'color': textColor}">
    <p class="m-0 whitespace-pre-wrap" [style]="{'color': textColor}">
        {{ content }}
    </p>
</div>

// CloudBoard.Vue/src/views/cloudboard/nodes/SimpleNote.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { Node } from '@/models/cloudboard';
import { useNodeProperty } from '@/composables/useNodeProperty';

const props = defineProps<{ node: Node }>();
const { getProperty, updateProperty } = useNodeProperty(() => props.node);

const content = computed({
  get: () => getProperty<string>('content', 'Empty note...'),
  set: (value) => updateProperty('content', value),
});
const backgroundColor = computed(() => getProperty<string>('backgroundColor', 'rgb(255, 249, 212)'));
const textColor = computed(() => getProperty<string>('textColor', '#000000'));
</script>

<template>
  <div class="simple-note shadow-md" :style="{ 'background-color': backgroundColor, color: textColor }">
    <p class="m-0 whitespace-pre-wrap" :style="{ color: textColor }">
      {{ content }}
    </p>
  </div>
</template>

<style scoped>
.simple-note {
  min-height: 10em;
  padding: 1rem;
  min-width: 20rem;
  max-width: 20rem;
}
</style>
