// CloudBoard.Angular/src/app/cloudboard/toolbar/toolbar.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { FlowControlService } from '../services/flow-control.service';
import { ToolbarModule } from 'primeng/toolbar';
import { ButtonModule } from 'primeng/button';

@Component({
  selector: 'toolbar',
  imports: [
    ButtonModule,
    ToolbarModule
  ],
  providers: [
  ],
  templateUrl: './toolbar.component.html',
  styleUrl: './toolbar.component.css'
})
export class ToolbarComponent implements OnInit {

  flowControlService: FlowControlService = inject(FlowControlService);

  constructor() { }

  ngOnInit(): void {
  }
}

<!-- Vertical toolbar. -->
<p-toolbar class="mt-3">
    <ng-template #center>
        <p-button icon="pi pi-fw pi-search-plus" text severity="secondary" (click)="flowControlService.zoomIn()">
        </p-button>
        <p-button icon="pi pi-fw pi-search-minus" text severity="secondary" (click)="flowControlService.zoomOut()">
        </p-button>
        <p-button icon="pi pi-fw pi-times-circle" text severity="secondary" (click)="flowControlService.resetZoom()">
        </p-button>
    </ng-template>
</p-toolbar>

// CloudBoard.Vue/src/views/cloudboard/Toolbar.vue
<script setup lang="ts">
import Toolbar from 'primevue/toolbar';
import Button from 'primevue/button';
import { useFlowControlStore } from '@/stores/flowControl';

const flowControlStore = useFlowControlStore();
</script>

<template>
  <Toolbar class="mt-3 board-toolbar">
    <template #center>
      <Button icon="pi pi-fw pi-search-plus" text severity="secondary" @click="flowControlStore.zoomIn()" />
      <Button icon="pi pi-fw pi-search-minus" text severity="secondary" @click="flowControlStore.zoomOut()" />
      <Button icon="pi pi-fw pi-times-circle" text severity="secondary" @click="flowControlStore.resetZoom()" />
    </template>
  </Toolbar>
</template>

<style scoped>
.board-toolbar {
  position: fixed;
  z-index: 10;
  margin: 2em 3em;
  pointer-events: none;
}

.board-toolbar :deep(.p-toolbar) {
  display: inline-flex;
  padding: 0;
  pointer-events: all;
}

.board-toolbar :deep(.p-toolbar-center) {
  flex-direction: column;
}
</style>
