// CloudBoard.Vue/src/views/cloudboard/PropertiesPanel.vue
<script setup lang="ts">
import Button from 'primevue/button';
import InputText from 'primevue/inputtext';
import Textarea from 'primevue/textarea';
import Inplace from 'primevue/inplace';
import ColorPicker from 'primevue/colorpicker';
import Select from 'primevue/select';
import ToggleSwitch from 'primevue/toggleswitch';
import { type LinkProperties, type Node, NodeType } from '@/models/cloudboard';
import * as nodeService from '@/services/nodeService';

const visible = defineModel<boolean>('visible', { default: false });
const nodeProperties = defineModel<Node | undefined>('nodeProperties', { default: undefined });

const nodeTypes = Object.values(NodeType);
const nodeTypeLabels: Record<NodeType, string> = {
  [NodeType.Note]: 'Simple Note',
  [NodeType.Card]: 'Card',
  [NodeType.LinkCollection]: 'Link Collection',
  [NodeType.ImageNode]: 'Image',
  [NodeType.CodeBlock]: 'Code Block',
};

const languageOptions = [
  { name: 'JavaScript', value: 'javascript' },
  { name: 'TypeScript', value: 'typescript' },
  { name: 'HTML', value: 'html' },
  { name: 'CSS', value: 'css' },
  { name: 'Python', value: 'python' },
  { name: 'Java', value: 'java' },
  { name: 'C#', value: 'csharp' },
  { name: 'JSON', value: 'json' },
];

function getNodeTypeLabel(type: NodeType): string {
  return nodeTypeLabels[type] || 'Unknown Type';
}

function changeNodeType(newType: NodeType): void {
  const node = nodeProperties.value;
  if (!node) return;

  const { id, name, position, connectors } = node;

  node.type = newType;
  node.properties = nodeService.getDefaultPropertiesForType(newType);

  node.id = id;
  node.name = name;
  node.position = position;
  node.connectors = connectors;

  void nodeService.updateNode(id, node);
}

function addLink(): void {
  const node = nodeProperties.value;
  if (!node || node.type !== NodeType.LinkCollection) return;

  const links: LinkProperties[] = node.properties['links'] || [];
  links.push({ title: 'New Link', url: 'https://example.com', iconClass: 'pi pi-external-link' });
  node.properties['links'] = links;

  void nodeService.updateNode(node.id, node);
}

function removeLink(index: number): void {
  const node = nodeProperties.value;
  if (!node || node.type !== NodeType.LinkCollection) return;

  const links: LinkProperties[] = node.properties['links'] || [];
  links.splice(index, 1);
  node.properties['links'] = links;

  void nodeService.updateNode(node.id, node);
}

function updateNodeName(name: string): void {
  const node = nodeProperties.value;
  if (!node || !name) return;

  node.name = name;
  void nodeService.updateNode(node.id, node);
}

function updateProperty(): void {
  const node = nodeProperties.value;
  if (!node) return;
  void nodeService.updateNode(node.id, node);
}
</script>

<template>
  <div
    class="sidepanel shadow-md bg-white h-full w-70 z-30 transition-all duration-200 ease-in-out"
    :class="visible ? 'open' : 'close'"
  >
    <div class="p-4">
      <div class="flex justify-between items-center mb-4">
        <Inplace class="w-full">
          <template #display>
            <h3 class="w-full text-xl truncate font-bold">{{ nodeProperties?.name }}</h3>
          </template>
          <template #content="{ closeCallback }">
            <input
              v-if="nodeProperties"
              type="text"
              class="p-inputtext"
              autofocus
              v-blur-on-enter
              v-model="nodeProperties.name"
              placeholder="Enter name"
              @blur="
                updateNodeName(nodeProperties!.name);
                closeCallback();
              "
            />
          </template>
        </Inplace>
        <Button text severity="contrast" class="toggle-btn" @click="visible = !visible">
          <i class="pi" :class="visible ? 'pi-chevron-right' : 'pi-chevron-left'"></i>
        </Button>
      </div>

      <div v-if="nodeProperties" class="properties-content">
        <!-- Node Type Selector -->
        <div class="field mb-4">
          <label class="block mb-1 font-medium">Node Type</label>
          <Select
            :options="nodeTypes"
            v-model="nodeProperties.type"
            class="w-full"
            @change="changeNodeType(nodeProperties.type)"
          >
            <template #value="{ value }">
              <div class="flex align-items-center gap-2">
                <span>{{ getNodeTypeLabel(value) }}</span>
              </div>
            </template>
            <template #option="{ option }">
              <div class="flex align-items-center gap-2">
                <span>{{ getNodeTypeLabel(option) }}</span>
              </div>
            </template>
          </Select>
        </div>

        <!-- Dynamic properties based on node type -->
        <div v-if="nodeProperties.type === NodeType.Note" class="node-properties">
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Content</label>
            <Textarea
              v-model="nodeProperties.properties['content']"
              auto-resize
              rows="5"
              class="w-full"
              @update:model-value="updateProperty"
            />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Background Color</label>
            <ColorPicker
              v-model="nodeProperties.properties['backgroundColor']"
              default-color="#f8f9fa"
              @update:model-value="updateProperty"
            />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Text Color</label>
            <ColorPicker
              v-model="nodeProperties.properties['textColor']"
              default-color="#212529"
              @update:model-value="updateProperty"
            />
          </div>
        </div>

        <div v-else-if="nodeProperties.type === NodeType.Card" class="node-properties">
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Title</label>
            <InputText v-model="nodeProperties.properties['title']" class="w-full" @update:model-value="updateProperty" />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Subtitle</label>
            <InputText
              v-model="nodeProperties.properties['subtitle']"
              class="w-full"
              @update:model-value="updateProperty"
            />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Image URL</label>
            <InputText
              v-model="nodeProperties.properties['imageUrl']"
              class="w-full"
              @update:model-value="updateProperty"
            />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Content</label>
            <Textarea
              v-model="nodeProperties.properties['content']"
              auto-resize
              rows="5"
              class="w-full"
              @update:model-value="updateProperty"
            />
          </div>
        </div>

        <div v-else-if="nodeProperties.type === NodeType.LinkCollection" class="node-properties">
          <div class="field mb-2 flex justify-between items-center">
            <label class="font-medium">Links</label>
            <Button icon="pi pi-plus" size="small" @click="addLink" />
          </div>

          <div
            v-for="(link, index) in (nodeProperties.properties['links'] as LinkProperties[])"
            :key="index"
            class="mb-4 p-3 border rounded shadow-sm"
          >
            <div class="flex justify-between items-center mb-2">
              <span class="text-sm font-bold">Link No. #{{ index }}</span>
              <Button icon="pi pi-trash" size="small" severity="danger" @click="removeLink(index)" />
            </div>

            <div class="field mb-2">
              <label class="block mb-1 text-sm">Title</label>
              <InputText v-model="link.title" class="w-full" @update:model-value="updateProperty" />
            </div>
            <div class="field mb-2">
              <label class="block mb-1 text-sm">URL</label>
              <InputText v-model="link.url" class="w-full" @update:model-value="updateProperty" />
            </div>
            <div class="field mb-2">
              <label class="block mb-1 text-sm">Icon Class</label>
              <InputText v-model="link.iconClass" class="w-full" @update:model-value="updateProperty" />
            </div>
          </div>
        </div>

        <div v-else-if="nodeProperties.type === NodeType.ImageNode" class="node-properties">
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Image URL</label>
            <InputText v-model="nodeProperties.properties['url']" class="w-full" @update:model-value="updateProperty" />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Alt Text</label>
            <InputText v-model="nodeProperties.properties['alt']" class="w-full" @update:model-value="updateProperty" />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Caption</label>
            <InputText
              v-model="nodeProperties.properties['caption']"
              class="w-full"
              @update:model-value="updateProperty"
            />
          </div>
        </div>

        <div v-else-if="nodeProperties.type === NodeType.CodeBlock" class="node-properties">
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Language</label>
            <Select
              :options="languageOptions"
              v-model="nodeProperties.properties['language']"
              option-label="name"
              option-value="value"
              class="w-full"
              @update:model-value="updateProperty"
            />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Show Line Numbers</label>
            <ToggleSwitch v-model="nodeProperties.properties['showLineNumbers']" @update:model-value="updateProperty" />
          </div>
          <div class="field mb-3">
            <label class="block mb-1 font-medium">Code</label>
            <Textarea
              v-model="nodeProperties.properties['code']"
              auto-resize
              rows="8"
              class="w-full font-mono text-sm"
              @update:model-value="updateProperty"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.sidepanel {
  --panel-open-width: 17.5rem;
  transform: translateX(100%);
}

.open {
  width: var(--panel-open-width);
  transform: translateX(0);
}

.close {
  width: 0;
  transform: translateX(100%);
}
</style>

// CloudBoard.Angular/src/app/cloudboard/properties-panel/properties-panel.component.ts
import { Component, model, inject } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { InplaceModule } from 'primeng/inplace';
import { NgClass } from '@angular/common';
import { Node, NodeType } from '../models/cloudboard';
import { BlurOnEnterDirective } from '../../helpers/blur-on-enter.directive';
import { TextareaModule } from 'primeng/textarea';
import { ColorPickerModule } from 'primeng/colorpicker';
import { NodeService } from '../services/node.service';
import { SelectModule } from 'primeng/select';
import { CheckboxModule } from 'primeng/checkbox';
import { ToggleSwitchModule } from 'primeng/toggleswitch';

@Component({
  selector: 'properties-panel',
  imports: [
    ButtonModule,
    FormsModule,
    InputTextModule,
    TextareaModule,
    InplaceModule,
    NgClass,
    ColorPickerModule,
    SelectModule,
    CheckboxModule,
    ToggleSwitchModule,
    BlurOnEnterDirective
  ],
  templateUrl: './properties-panel.component.html',
  styleUrl: './properties-panel.component.css'
})
export class PropertiesPanelComponent {
  visible = model<boolean>(false);
  nodeProperties = model<Node|undefined>(undefined);

  nodeTypes = Object.values(NodeType);
  nodeTypeLabels: Record<NodeType, string> = {
    [NodeType.Note]: 'Simple Note',
    [NodeType.Card]: 'Card',
    [NodeType.LinkCollection]: 'Link Collection',
    [NodeType.ImageNode]: 'Image',
    [NodeType.CodeBlock]: 'Code Block'
  };
  
  languageOptions = [
    { name: 'JavaScript', value: 'javascript' },
    { name: 'TypeScript', value: 'typescript' },
    { name: 'HTML', value: 'html' },
    { name: 'CSS', value: 'css' },
    { name: 'Python', value: 'python' },
    { name: 'Java', value: 'java' },
    { name: 'C#', value: 'csharp' },
    { name: 'JSON', value: 'json' }
  ];

  private nodeService = inject(NodeService);

  changeNodeType(newType: NodeType): void {
    if (this.nodeProperties()) {
      // Store current node properties that shouldn't change
      const node = this.nodeProperties()!;
      const id = node.id;
      const name = node.name;
      const position = node.position;
      const connectors = node.connectors;
      
      // Update the node type and set default properties for that type
      node.type = newType;
      node.properties = this.nodeService.getDefaultPropertiesForType(newType);
      
      // Restore unchanged properties
      node.id = id;
      node.name = name;
      node.position = position;
      node.connectors = connectors;
      
      // Update the node via API
      this.nodeService.updateNode(id, node).subscribe();
    }
  }

  getNodeTypeLabel(type: any): string {
    return this.nodeTypeLabels[type as NodeType] || 'Unknown Type';
  }
  
  addLink(): void {
    if (this.nodeProperties() && this.nodeProperties()!.type === NodeType.LinkCollection) {
      const node = this.nodeProperties()!;
      const links = node.properties['links'] || [];
      links.push({ title: 'New Link', url: 'https://example.com', iconClass: 'pi pi-external-link' });
      node.properties['links'] = links;
      
      // Update the node via API
      this.nodeService.updateNode(node.id, node).subscribe();
    }
  }
  
  removeLink(index: number): void {
    if (this.nodeProperties() && this.nodeProperties()!.type === NodeType.LinkCollection) {
      const node = this.nodeProperties()!;
      const links = node.properties['links'] || [];
      links.splice(index, 1);
      node.properties['links'] = links;
      
      // Update the node via API
      this.nodeService.updateNode(node.id, node).subscribe();
    }
  }

  // Method to handle node name updates
  updateNodeName(name: string): void {
    if (this.nodeProperties() && name) {
      const node = this.nodeProperties()!;
      node.name = name;
      
      // Update the node via API
      this.nodeService.updateNode(node.id, node).subscribe();
    }
  }
}

<div class="sidepanel shadow-md bg-white h-full w-70 z-30 transition-all duration-200 ease-in-out" [class.open]="visible()" [class.close]="!visible()">
    <div class="p-4">
        <div class="flex justify-between items-center mb-4">
            <p-inplace class="w-full">
                <ng-template #display>
                    <h3 class="w-full text-xl truncate font-bold">{{ nodeProperties()?.name }}</h3>
                </ng-template>
                <ng-template #content let-closeCallback="closeCallback">
                    <input type="text" pInputText autofocus blurOnEnter [(ngModel)]="nodeProperties()!.name" 
                           (blur)="updateNodeName(nodeProperties()!.name); closeCallback($event)" 
                           placeholder="Enter name" />
                </ng-template>
            </p-inplace>
            <p-button text severity="contrast" class="toggle-btn" (click)="visible.set(!visible())">
                <i class="pi" [ngClass]="visible() ? 'pi-chevron-right' : 'pi-chevron-left'"></i>
            </p-button>
        </div>
        
        @if (nodeProperties()) {
        <div class="properties-content">
            <!-- Node Type Selector -->
            <div class="field mb-4">
                <label class="block mb-1 font-medium">Node Type</label>
                <p-select
                    [options]="nodeTypes"
                    [(ngModel)]="nodeProperties()!.type"
                    optionLabel=""
                    [optionValue]="''"
                    class="w-full"
                    (onChange)="changeNodeType($event.value)">
                    <ng-template #selectedItem>
                        <div class="flex align-items-center gap-2">
                            <span>{{ getNodeTypeLabel( nodeProperties()!.type) }}</span>
                        </div>
                    </ng-template>
                    <ng-template #item let-type>
                        <div class="flex align-items-center gap-2">
                            <span>{{ getNodeTypeLabel(type) }}</span>
                        </div>
                    </ng-template>
                </p-select>
            </div>
            
            <!-- Dynamic properties based on node type -->
             @switch(nodeProperties()!.type) {
                @case ('Note') {
                <!-- Simple Note Properties -->
                <div class="node-properties">
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Content</label>
                        <textarea 
                            pInputTextarea 
                            [(ngModel)]="nodeProperties()!.properties['content']" 
                            autoResize="true"
                            rows="5" 
                            class="w-full">
                        </textarea>
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Background Color</label>
                        <p-colorPicker 
                            [(ngModel)]="nodeProperties()!.properties['backgroundColor']"
                            defaultColor="#f8f9fa">
                        </p-colorPicker>
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Text Color</label>
                        <p-colorPicker 
                            [(ngModel)]="nodeProperties()!.properties['textColor']"
                            defaultColor="#212529">
                        </p-colorPicker>
                    </div>
                </div>
                }
                @case ('Card') {
                <!-- Card Node Properties -->
                <div class="node-properties">
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Title</label>
                        <input 
                            type="text" 
                            pInputText 
                            [(ngModel)]="nodeProperties()!.properties['title']" 
                            class="w-full" />
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Subtitle</label>
                        <input 
                            type="text" 
                            pInputText 
                            [(ngModel)]="nodeProperties()!.properties['subtitle']" 
                            class="w-full" />
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Image URL</label>
                        <input 
                            type="text" 
                            pInputText 
                            [(ngModel)]="nodeProperties()!.properties['imageUrl']" 
                            class="w-full" />
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Content</label>
                        <textarea 
                            pInputTextarea 
                            [(ngModel)]="nodeProperties()!.properties['content']" 
                            autoResize="true"
                            rows="5" 
                            class="w-full">
                        </textarea>
                    </div>
                </div>
                }
                @case ('LinkCollection') {
                <!-- Link Collection Properties -->
                <div class="node-properties">
                    <div class="field mb-2 flex justify-between items-center">
                        <label class="font-medium">Links</label>
                        <p-button 
                            icon="pi pi-plus" 
                            size="small" 
                            (onClick)="addLink()">
                        </p-button>
                    </div>
                    
                    @for (link of nodeProperties()!.properties['links']; track $index) {
                    <div class="mb-4 p-3 border rounded shadow-sm">
                        <div class="flex justify-between items-center mb-2">
                            <span class="text-sm font-bold">Link No. #{{ $index }}</span>
                            <p-button 
                                icon="pi pi-trash" 
                                size="small" 
                                severity="danger"
                                (onClick)="removeLink($index)">
                            </p-button>
                        </div>
                        
                        <div class="field mb-2">
                            <label class="block mb-1 text-sm">Title</label>
                            <input 
                                type="text" 
                                pInputText 
                                [(ngModel)]="link.title" 
                                class="w-full" />
                        </div>
                        
                        <div class="field mb-2">
                            <label class="block mb-1 text-sm">URL</label>
                            <input 
                                type="text" 
                                pInputText 
                                [(ngModel)]="link.url" 
                                class="w-full" />
                        </div>
                        
                        <div class="field mb-2">
                            <label class="block mb-1 text-sm">Icon Class</label>
                            <input 
                                type="text" 
                                pInputText 
                                [(ngModel)]="link.iconClass" 
                                class="w-full" />
                        </div>
                    </div>
                    }
                </div>
                }
                @case ('ImageNode') {
                <!-- Image Node Properties -->
                <div class="node-properties">
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Image URL</label>
                        <input 
                            type="text" 
                            pInputText 
                            [(ngModel)]="nodeProperties()!.properties['url']" 
                            class="w-full" />
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Alt Text</label>
                        <input 
                            type="text" 
                            pInputText 
                            [(ngModel)]="nodeProperties()!.properties['alt']" 
                            class="w-full" />
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Caption</label>
                        <input 
                            type="text" 
                            pInputText 
                            [(ngModel)]="nodeProperties()!.properties['caption']" 
                            class="w-full" />
                    </div>
                </div>
                }
                @case('CodeBlock') {
                <!-- Code Block Properties -->
                <div class="node-properties">
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Language</label>
                        <p-select
                            [options]="languageOptions"
                            [(ngModel)]="nodeProperties()!.properties['language']"
                            optionLabel="name"
                            optionValue="value"
                            class="w-full">
                        </p-select>
                    </div>

                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Show Line Numbers</label>
                        <p-toggleswitch [(ngModel)]="nodeProperties()!.properties['showLineNumbers']"></p-toggleswitch>
                    </div>
                    
                    <div class="field mb-3">
                        <label class="block mb-1 font-medium">Code</label>
                        <textarea 
                            pInputTextarea 
                            [(ngModel)]="nodeProperties()!.properties['code']" 
                            autoResize="true"
                            rows="8" 
                            class="w-full font-mono text-sm">
                        </textarea>
                    </div>
                </div>
                }
            }
        </div>
        }
    </div>
</div>
